name: "CI: macOS"

on: [ push, pull_request ]

jobs:
  macos-test:
    runs-on: macos-latest
    strategy:
      matrix:
        CPP_VERSION: [ 17, 20 ]
    steps:
      - uses: actions/checkout@v2

      - name: Install CMake
        shell: bash
        run: brew install cmake

      - name: Install Ninja
        shell: bash
        run: brew install ninja

      - name: Install GLFW
        shell: bash
        run: brew install glfw

      - name: Install SDL2
        shell: bash
        run: |
          brew install sdl2
          brew install sdl2_image
          brew install sdl2_mixer
          brew install sdl2_ttf

      - name: Make build directory
        shell: bash
        run: mkdir build

      - name: Build
        working-directory: ./build
        shell: bash
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=${{matrix.CPP_VERSION}} -DCEN_TESTS=ON -GNinja
          ninja

      - name: Run unit tests
        working-directory: ./build/test/unit-tests
        shell: bash
        run: ./testcenturion

      - name: Run mocked test suite
        working-directory: ./build/test/mocked-tests
        shell: bash
        run: ./mockcenturion
