name: "CI: Ubuntu"

on: [ push ]

env:
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/vcpkg/bincache
  SDL_VIDEODRIVER: x11
  DISPLAY: :99.0

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip-ci]') == false
    strategy:
      matrix:
        SDL_VERSION: [ 2.0.20, 2.0.22, 2.24.0, 2.26.0 ]
        CPP_VERSION: [ 17, 20 ]
        include:
          - SDL_VERSION: 2.0.10
            CPP_VERSION: 17
          - SDL_VERSION: 2.0.12
            CPP_VERSION: 17
          - SDL_VERSION: 2.0.14
            CPP_VERSION: 17
          - SDL_VERSION: 2.0.16
            CPP_VERSION: 17
          - SDL_VERSION: 2.0.18
            CPP_VERSION: 17
          - SDL_VERSION: 2.26.0
            CPP_VERSION: 23
    steps:
      - uses: actions/checkout@main
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: lukka/get-cmake@latest

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install ninja-build \
                           xvfb \
                           gnome-desktop-testing \
                           libasound2-dev \
                           libpulse-dev \
                           libaudio-dev \
                           libjack-dev \
                           libsndio-dev \
                           libsamplerate0-dev \
                           libx11-dev \
                           libxext-dev \
                           libxrandr-dev \
                           libxcursor-dev \
                           libxfixes-dev \
                           libxi-dev \
                           libxss-dev \
                           libwayland-dev \
                           libxkbcommon-dev \
                           libdrm-dev \
                           libgbm-dev \
                           libgl1-mesa-dev \
                           libgles2-mesa-dev \
                           libegl1-mesa-dev \
                           libdbus-1-dev \
                           libibus-1.0-dev \
                           libudev-dev \
                           fcitx-libs-dev \
                           libpipewire-0.3-dev \
                           libdecor-0-dev \
                           libsdl2-image-dev \
                           libsdl2-mixer-dev \
                           libsdl2-ttf-dev

      - name: Restore Vcpkg
        id: restore-vcpkg-and-artifacts
        uses: actions/cache@v3
        with:
          path: |
            ${{env.VCPKG_ROOT}}
            !${{env.VCPKG_ROOT}}/buildtrees
            !${{env.VCPKG_ROOT}}/packages
            !${{env.VCPKG_ROOT}}/downloads
            !${{env.VCPKG_ROOT}}/installed
          key: centurion-ubuntu-vcpkg-${{hashFiles('vcpkg.json')}}

      - name: Install Vcpkg
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/microsoft/vcpkg
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
          sudo ./vcpkg/vcpkg integrate install

      - name: Create Vcpkg binary cache directory
        if: steps.restore-vcpkg-and-artifacts.outputs.cache-hit != 'true'
        run: mkdir ${{env.VCPKG_DEFAULT_BINARY_CACHE}}

      - name: Restore SDL2
        id: restore-sdl2
        uses: actions/cache@main
        with:
          path: SDL2-${{matrix.SDL_VERSION}}
          key: SDL2-${{matrix.SDL_VERSION}}

      - name: Build SDL2
        if: steps.restore-sdl2.outputs.cache-hit != 'true'
        run: |
          wget https://www.libsdl.org/release/SDL2-${{matrix.SDL_VERSION}}.tar.gz
          tar -xvf SDL2-${{matrix.SDL_VERSION}}.tar.gz
          cd SDL2-${{matrix.SDL_VERSION}}
          ./configure
          make -j $(nproc)

      - name: Install SDL2
        run: |
          cd SDL2-${{matrix.SDL_VERSION}}
          sudo make install

      - name: Emulate video device
        run: |
          /sbin/start-stop-daemon --start \
                                  --pidfile /tmp/custom_xvfb_99.pid \
                                  --make-pidfile \
                                  --background \
                                  --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX;
          sleep 3

      - name: Generate build files
        run: |
          mkdir build && cd build
          cmake .. -GNinja \
                   -DCMAKE_BUILD_TYPE=Debug \
                   -DCMAKE_CXX_STANDARD=${{matrix.CPP_VERSION}} \
                   -DBUILD_TESTS=ON \
                   -DBUILD_EXAMPLES=ON \
                   -DINCLUDE_AUDIO_TESTS=OFF

      - name: Build
        run: ninja -C build

      - name: Run mocked tests
        working-directory: ./build/test/mocked-tests
        run: ./mockcenturion

      - name: Run unit tests
        working-directory: ./build/test/unit-tests
        run: ./testcenturion
